### ISSUE TITLE
ordering_party_bank_clearing_number should be padded with blanks

### ISSUE THREAD

**Issue by senny** [phuesler/payment_dta#1]
according to the DTA specification the " Bankenclearing-Nr.  der Bank des Auftraggeber" should be padded with blanks. The current implementation paddes with 0. I wanted to ask, if this code is still used in production and if it is necessary to pad with blanks or zeros.

References:
www.bkb.ch/dta_dl_tkicch.pdf (Page 18)

**Comment by phuesler** [comment]
I think you're right, this looks like a bug. I should indeed be padded with blanks. To answer your question: I haven't used this code in years, so I simply don't know. A dta validator should answer this questions, however, I could not find one online.

Please feel free to fork the project and make your changes.

Cheers

Patrick

**Comment by senny** [comment]
Thanks for the immediate response :). I'll fork and make my changes as suggested. I just wanted to check wether this was intended or not.

**Comment by senny** [comment]
I just created a pull-request to fix the bug. It somehow created a new issue with the pull-request attached. I think I close this one for now. Progress ist at #4
